apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx-test
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  type: ClusterIP
